name: CI

on:
  pull_request:
    branches:
      - main


jobs:
  lint-models:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get changed SQL files
        id: changed-files
        uses: tj-actions/changed-files@v37
        with:
          files: dbt/models/**/*.sql
          separator: ' '

      - name: List changed SQL files
        run: |
          echo "Changed Files:";
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo $file
          done
        
      - name: Setup Python
        if: steps.changed-files.outputs.any_changed == 'true'  
        uses: actions/setup-python@v4
        with:
            python-version: '3.10'
            cache: 'pip'

      - name: Install dependencies
        if: steps.changed-files.outputs.any_changed == 'true'
        run: pip install -r requirements.txt

      - name: Install dbt deps
        if: steps.changed-files.outputs.any_changed == 'true'
        run: cd dbt && dbt deps

      - name: Lint dbt models
        if: steps.changed-files.outputs.any_changed == 'true'
        run: sqlfluff lint --format github-annotation --annotation-level failure --nofail ${{ steps.changed-files.outputs.all_changed_files }} > annotations.json

      - name: Annotate
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: yuzutech/annotations-action@v0.3.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          title: "SQLFluff Lint"
          input: "./annotations.json"
