name: CI

on:
  pull_request:
    branches:
      - main


jobs:
  lint-models:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37
        with:
          files: dbt/models/*.sql

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

      - name: Setup Python  
        uses: actions/setup-python@v4
        with:
            python-version: '3.10'
            cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install dbt deps
        run: cd dbt && dbt deps

      
      - name: Lint dbt models
        run: sqlfluff lint ./dbt/models

# jobs:
#   # -------------------------------------------------------------
#   # Event `pull_request`: Returns all changed pull request files.
#   # --------------------------------------------------------------
#   changed_files:
#     # NOTE:
#     # - This is limited to pull_request* events and would raise an error for other events.
#     # - A maximum of 3000 files can be returned.
#     # - For more flexibility and no limitations see "Using local .git history" above.

#     runs-on: ubuntu-latest  # windows-latest || macos-latest
#     name: Test changed-files
#     permissions:
#       pull-requests: read

#     steps:
#       - name: Get changed files
#         id: changed-files
#         uses: tj-actions/changed-files@v37

#       - name: List all changed files
#         run: |
#           for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
#             echo "$file was changed"
#           done