name: CI

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  lint-models:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python  
        uses: actions/setup-python@v4
        with:
            python-version: '3.10'
            cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install dbt deps
        run: cd dbt && dbt deps

      - name: Get Changed Files
        uses: tj-actions/changed-files@v37.4.0

      - name: List files
        run: |
          echo "All changed files: ${{ steps.changed-files.outputs.all_changed_files }}"

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

      - name: Lint dbt models
        run: sqlfluff lint ./dbt/models

      