name: Hello World Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Echo Hello World
      run: echo "Hello World"

   
  