name: dbt-runner

on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: '0 0 1 * *' # Once a month on the 1st
  workflow_dispatch: {} # Enable manual runs


jobs:
  dbt-run:
    runs-on: ubuntu-latest
    environment: production
    env:
      MY_SECRET: ${{ secrets.MY_SECRET }}
      MY_VARIABLE: ${{ vars.MY_VARIABLE }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.6.1
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install project dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root
      
      - name: Install dbt dependencies
        run: cd dbt && poetry run dbt deps

      - name: Run dbt
        run: cd dbt && poetry run dbt run --profiles-dir . --project-dir .

  dbt-docs:
    needs: dbt-run
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: pwd
      #   run: pwd

      # - name: List files
      #   run: ls -la
      
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-2

      - name: Upload files to S3
        run: |
          aws s3 sync /home/runner/work/duckdb-dbt/duckdb-dbt/.sqlfluff s3://duckdb-dbt-docs/
  